### ISSUE TITLE
test bedrock client performance

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#173]
https://github.com/ViaVersion/ViaProxy

I do not have access to a Windows machine right now so I can't try bedrock
... but it might make sense trying to support bedrock proto if they can support
*way* more players with reasonable FPS.

**Comment by TestingPlant** [comment]
Geyser is more popular for bedrock to java protocol translation, so we should also consider trying that

**Comment by andrewgazelka** [comment]
> Geyser

interesting will look into

**Comment by andrewgazelka** [comment]
I think I decided it makes sense to use Java—at least at first. There are way more Java players than Bedrock.
