### ISSUE TITLE
Remove panicing areas in code

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#192]
**include areas of flecs-ecs that can panic in C! There are a lot of cases players can send invalid packet (say with invalid entity IDs to crash the server!**

- also we panic if invalid ver is gotten

So, our code panics in a lot of areas where it shouldn't. And it should behave differently. Now, this isn't always ignoring the error. In some cases, we might want to, say, kick a player. Definitely log the message most of the time, especially if it's an internal error. So, this is very, very important. This needs to be done before we actually have this in production. This is a big issue, though. So, although this is labeled good first issue, I would definitely recommend probably it being a collaborative PR. So, maybe you make a PR and then make sure that other people have edit capabilities. So, other people can edit the PR, add on to the PR. Because there's, again, there's probably a lot of different places in the code that are using unwrap. Or have panic. Within the code somewhere. Even if it's hidden, kind of like slicing code.

- Might be helpful: https://docs.rs/no-panic/latest/no_panic/
- more lints, for instance to prevent panics with slicing, unwrap, expect

**Comment by andrewgazelka** [comment]
A lot of the panicking areas of the code occur in serialization because of valence

```rust
/// [macro]: valence_protocol_macros::Encode
/// [`VarInt`]: var_int::VarInt
pub trait Encode {
    /// Writes this object to the provided writer.
    ///
    /// If this type also implements [`Decode`] then successful calls to this
    /// function returning `Ok(())` must always successfully [`decode`] using
    /// the data that was written to the writer. The exact number of bytes
    /// that were originally written must be consumed during the decoding.
    ///
    /// [`decode`]: Decode::decode
    fn encode(&self, w: impl Write) -> anyhow::Result<()>;

    /// Like [`Encode::encode`], except that a whole slice of values is encoded.
    ///
    /// This method must be semantically equivalent to encoding every element of
    /// the slice in sequence with no leading length prefix (which is exactly
    /// what the default implementation does), but a more efficient
    /// implementation may be used.
    ///
    /// This method is important for some types like `u8` where the entire slice
    /// can be encoded in a single call to [`write_all`]. Because impl
    /// specialization is unavailable in stable Rust at the time of writing,
    /// we must make the slice specialization part of this trait.
    ///
    /// [`write_all`]: Write::write_all
    fn encode_slice(slice: &[Self], mut w: impl Write) -> anyhow::Result<()>
    where
        Self: Sized,
    {
        for value in slice {
            value.encode(&mut w)?;
        }

        Ok(())
    }
}
```

need to figure out what I want to do about this.

**Comment by BGR360** [comment]
Has any effort been made to date to try fuzzing the protocol server to find more panicking branches? Should that be an issue of its own for somebody to take on?

**Comment by andrewgazelka** [comment]
> Has any effort been made to date to try fuzzing the protocol server to find more panicking branches? Should that be an issue of its own for somebody to take on?

hmmmmm I think I decided this might not be as important as I thought. The panicking doesn't occur in the serialization logic (it returns an `anyhow` error)... it usually occurs when `unwrap`ing in `hyperion` code so much easier to just remove these unwraps and maybe kick the player or do something special if there is invalid data (or some smart logic).

However, sadly because all packets return `anyhow::Result` but very few actually ever return an `Err` variant it can be confusing where to put effort in detecting if a packet cannot be serialized.

I think prio before fuzzing or rewriting packet ser lib to be more explicit when there is error would be just making sure the rest of the existing code is validated and handles `Result`s correctly.

**Comment by andrewgazelka** [comment]
closing as low prio for now
