### ISSUE TITLE
git rid of majority of channels

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#205]

**Comment by TestingPlant** [comment]
I'm starting to wonder if removing monoio and using io-uring directly would be better. Io uring already has a submission and completion queue, and adding our own packet send queue and packet receive queue is adding more overhead.

My current plan for s2c packets is that we can add more write operations to the send queue without waiting for the previous write operation to finish. However, this would cause issues if only part of the data is written. From what I've read, this only occurs when a signal is sent which causes EINTR to be returned and when the tcp send buffer is full. I don't know if EINTR is still returned when using io uring, and for the send queue, we could detect if it's about to be full.

**Comment by andrewgazelka** [comment]
> I'm starting to wonder if removing monoio and using io-uring directly would be better. Io uring already has a submission and completion queue, and adding our own packet send queue and packet receive queue is adding more overhead.
> 
> My current plan for s2c packets is that we can add more write operations to the send queue without waiting for the previous write operation to finish. However, this would cause issues if only part of the data is written. From what I've read, this only occurs when a signal is sent which causes EINTR to be returned and when the tcp send buffer is full. I don't know if EINTR is still returned when using io uring, and for the send queue, we could detect if it's about to be full.

I'm down for this (and only supporting Linux + io_uring) if we can figure it out and bench it.

**Comment by andrewgazelka** [comment]
we are not using any channels afaik since we have started using io uring
