### ISSUE TITLE
decide which ECS to use

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#350]
I think we should do a lot of research.
I like `evenio` but I think we might need a multi-threaded ECS at some point.
At the same time we need to make sure it works properly. Often these ECSs have a lot of overhead.

look at https://github.com/valence-rs/valence/issues/596

**Comment by Ruben2424** [comment]
Here is a list of some, that i found in a quick search. But i didn't take a close look yet.

Parallel ones according to readme:
https://github.com/ten3roberts/flax
https://github.com/amethyst/specs
https://github.com/amethyst/legion
https://github.com/Bergmann89/async-ecs

Need to find out if they are Parallel or not:
https://github.com/AnneKitsune/planck_ecs
https://github.com/Ralith/hecs
https://github.com/JohanNorberg/zero_ecs
https://github.com/ABC-Engine/ABC-ECS

**Comment by andrewgazelka** [comment]
I'm also not completely against using bevy.

**Comment by andrewgazelka** [comment]
also alternatively could try to improve `evenio`

**Comment by andrewgazelka** [comment]
we decided to use `flecs`. :)
