### ISSUE TITLE
dynamic lighting

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#381]
Ideally, we want to calculate server lighting and we want it to be taxi cab distance.

**Comment by TestingPlant** [comment]
I think we'd be able to get away with just having a max light level on everything. I believe most people play with fullbright on minigame servers anyways (don't have a source for this) so nobody would really notice.

**Comment by TheDevMinerTV** [comment]
I guess you could implement some sort of light baking like most game engines do already. You could embed the light map into the world file since the world isn't gonna change during play.

**Comment by andrewgazelka** [comment]
> I think we'd be able to get away with just having a max light level on everything. I believe most people play with fullbright on minigame servers anyways (don't have a source for this) so nobody would really notice.

yea I would say this probably isn't priority now but something that maybe we want to implement in the future.

**Comment by andrewgazelka** [comment]
we are using pre-generated lighting. dynamic lighting not prio for MVP.
