### ISSUE TITLE
fix edge cases which allow clients to create new items

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#417]

**Comment by andrewgazelka** [comment]
can anyone work on this? checking inventory is going to be a super important thing in the event and I want to allow people to rearrange items

**Comment by andrewgazelka** [comment]
not sure this is super relevant as we have static or static like inventory

**Comment by Kumpelinus** [comment]
@andrewgazelka I was able to dupe blocks in the past tho. And they actually worked as they should. So I don't know whether this is really irrelevant.

**Comment by andrewgazelka** [comment]
> @andrewgazelka I was able to dupe blocks in the past tho. And they actually worked as they should. So I don't know whether this is really irrelevant.

hmmm yea let's watch out for it. feel free to make fixes still. just don't want to focus on yet
