### ISSUE TITLE
panic if client sends to many packets

### ISSUE THREAD

**Issue by Ruben2424** [andrewgazelka/hyperion#439]
```rs
thread 'main' panicked at crates/server/src/system/ingress.rs:92:55:
called `Result::unwrap()` on an `Err` value: CapacityError: insufficient capacity
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

this is because `push()` panics if there is not enough capacity.
https://github.com/andrewgazelka/hyperion/blob/d79f5de48a0ab74945ba5565d968463c9a778f14/crates/server/src/system/ingress.rs#L92

This is triggered for example when the client drags many items in inventory, because for each item in a slot one packet is sent.
We can use `try_push()`, this will not panic but gives back an error.

Should we have a limit here? 
If yes how big?

**Comment by andrewgazelka** [comment]
closing this as old and not relevant anymore post-recode
