### ISSUE TITLE
arrows don't collide with entities

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#446]

**Comment by TestingPlant** [comment]
I'm not sure what the best way to do this would be. There's three main types of entities:
- Players
- Arrows
- Dropped items

Is there a good way to handle collisions between any of these types of entities while still being extensible through ECS? Right now I can only think of using an enum for determining a collision behavior.

**Comment by andrewgazelka** [comment]
> I'm not sure what the best way to do this would be. There's three main types of entities:
> 
> * Players
> * Arrows
> * Dropped items
> 
> Is there a good way to handle collisions between any of these types of entities while still being extensible through ECS? Right now I can only think of using an enum for determining a collision behavior.

yea I think we could use some type of bitset that would include entity properties say like collision behavior

**Comment by andrewgazelka** [comment]
closing this as old and not relevant anymore as does not exist post recode
