### ISSUE TITLE
Vanilla arrow/item release behavior

### ISSUE THREAD

**Issue by eduxstad** [andrewgazelka/hyperion#456]
https://github.com/andrewgazelka/hyperion/blob/dbccf3e867bf3a1f8769a184ec4099e3bfe9beb1/crates/server/src/system/release_item.rs#L48-L61

Right now arrows don't get released from the right spot. This is obvious when comparing to vanilla/singleplayer. We should update this to be more accurate to vanilla behavior.

## Tasks
- [ ] Determine exact vanilla behavior somehow (RE, other implementations)?
- [ ] Update `release_item.rs`

**Comment by andrewgazelka** [comment]
I'm going to use the deobfuscated 1.20.1 mappings.

https://github.com/mat-1/DecompilerMC

**Comment by TestingPlant** [comment]
I got the correct offset using pakkit earlier but didn't push my changes yet. I'll update it in a minute

**Comment by andrewgazelka** [comment]
closing this as not planned as not needed for MVP. will potentially open later.
