### ISSUE TITLE
Pumpkin does support more

### ISSUE THREAD

**Issue by Snowiiii** [andrewgazelka/hyperion#485]
Saw you have a comparison between some Server softwares
![image](https://github.com/user-attachments/assets/7d5e0f17-b7b0-49f5-ac90-3b8b9528bef6)
Wanted to note that Pumpkin does in fact support more features than listed

**Comment by andrewgazelka** [comment]
Please feel free to PR if something is missing/incorrect.

**Comment by andrewgazelka** [comment]
ok let's go over it. If you update your README I can update this repo better https://github.com/Snowiiii/Pumpkin

![Pumpkin](https://github.com/user-attachments/assets/55113939-c572-4060-8e6f-771d8abf7bbc)

Above is pumpkin when I join the server.

- **has been tested with thousands of player connects.** I have not seen this. if you have evidence it can run 5k bot connections at 20TPS all where they can see each other (or similar) I will change this. However, joining in your server with multiple clients I do not even see the other players!
- **proximity voice chat** quite sure you do not have this
- **lighting** based on the image does not appear to work
- **placing blocks** I cannot seem to find out how to get blocks. destroying blocks is not putting them in my inventory
- **destroying blocks** likewise having issues here too. the blocks do not go in my inventory. I'm unsure if the server is even handling the packets
- ... 

unsure if these worked at some point. However, most of these do not work now. I do see I got the Minecraft version wrong so I will change that.

**Comment by andrewgazelka** [comment]
I am closing this, but if I see any big changes in your server, I will make sure to update where appropriate—good job on your project.
