### ISSUE TITLE
Disable Nagle's algorithm on TCP sockets

### ISSUE THREAD

**Issue by BGR360** [andrewgazelka/hyperion#487]
For latency-sensitive applications that run on relatively reliable networks (i.e., not on laptops with crappy WiFi), the consensus seems to be that disabling Nagle's algorithm by setting `TCP_NODELAY` is the right thing to do.

Simply add (a) call(s) to [`TcpStream::set_nodelay(true)`](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.set_nodelay) wherever applicable.

The only way this would cause a problem is if you're doing really small writes to the socket. But I imagine Hyperion takes care to buffer data and avoid this.

Here are some more resources I found to read up on this:
- [It’s always TCP_NODELAY. Every damn time.](https://brooker.co.za/blog/2024/05/09/nagle.html)
- [Go disables Nagle's Algorithm by default](https://news.ycombinator.com/item?id=34179426)

**Comment by andrewgazelka** [comment]
> For latency-sensitive applications that run on relatively reliable networks (i.e., not on laptops with crappy WiFi), the consensus seems to be that disabling Nagle's algorithm by setting `TCP_NODELAY` is the right thing to do.
> 
> Simply add (a) call(s) to [`TcpStream::set_nodelay(true)`](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.set_nodelay) wherever applicable.
> 
> The only way this would cause a problem is if you're doing really small writes to the socket. But I imagine Hyperion takes care to buffer data and avoid this.
> 
> Here are some more resources I found to read up on this:
> 
> * [It’s always TCP_NODELAY. Every damn time.](https://brooker.co.za/blog/2024/05/09/nagle.html)
> * [Go disables Nagle's Algorithm by default](https://news.ycombinator.com/item?id=34179426)

Thanks for the analysis.

Right now the 
- **game server** is doing _massive_ writes (writing all buffers at the end of the gametick) and (probably) tiny-ish reads. All over a local network. 
- **proxy** is more of a mix and communicates between the game server and players.

---

I will look into this later. If you would like to make a PR I will likely accept it. Also if you want to bench `just bots {number_bots}` command works very well

**Comment by BGR360** [comment]
This would be more impactful for the `Proxy --> Player` traffic which goes over the WAN and may have unpredictable latency. Probably will not make a difference with the `Game Server <--> Proxy` traffic over LAN, but wouldn't hurt.

**Comment by BGR360** [comment]
A note to whoever does this and attempts to benchmark it: likely need to introduce artificial latency between the proxies and bot connections in order to observe any improvement. And the measure of how well this helps will be in the perceived latency from the player's point of view.

**Comment by andrewgazelka** [comment]
> A note to whoever does this and attempts to benchmark it: likely need to introduce artificial latency between the proxies and bot connections in order to observe any improvement. And the measure of how well this helps will be in the perceived latency from the player's point of view.

Any recommended way to do this? I know there are some tool but have never used before. also do not feel like buying multiple dedis to test this (at least until closer to event).

**Comment by BGR360** [comment]
> I know there are some tools to add latency but have never used before

I haven't either, sorry.
