### ISSUE TITLE
Doors (Cannot move into solid blocks)

### ISSUE THREAD

**Issue by CuzImClicks** [andrewgazelka/hyperion#524]
While walking into a door in its closed state, then opening it while still walking against it you get this message:

`Cannot move into solid blocks`

**Comment by andrewgazelka** [comment]
This is just a system ordering issue. If movement is processed after doors have been opened, or after the open door logic has been processed, then I don't think this issue will occur.

**Comment by andrewgazelka** [comment]
we don't have doors in the map atm. going to close as not planned for now (might re-open later)
