### ISSUE TITLE
Support masking

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#58]
# Networking Packet Management in Gaming

In online, the handling of packets plays a crucial role in maintaining smooth gameplay and efficient network communication. One concern is the scenario where a player sends a packet that is then echoed back to them unnecessarily. While this may not immediately disrupt gameplay, it can lead to inefficiencies and potentially impact the player experience over time.

## Potential Issues
- **Redundant Data:** Receiving echoed packets can result in redundant data processing and network usage.
- **Bandwidth Consumption:** Unnecessary packet echoing can consume additional bandwidth without providing significant benefits.
- **Latency:** Increased traffic from echoed packets may contribute to higher latency in the gameplay experience.

## Recommendations
To optimize packet management and network efficiency, it is advisable to implement a masking mechanism in the networking logic. This mechanism would selectively filter out packets that do not require a response back to the originating player. By integrating this masking mechanism into the broadcast logic, developers can tailor the packet flow to prioritize relevant data transmission.

In essence, by masking specific packets intelligently, game developers can streamline network traffic, reduce unnecessary data processing, and ultimately enhance the overall gaming experience for players.

**Comment by TestingPlant** [comment]
Solved by #63
