### ISSUE TITLE
`/vanish` command

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#590]

**Comment by Kumpelinus** [comment]
I can try to figure out which packets might need to be adjusted to implement this.

**Comment by Kumpelinus** [comment]
Would vanish functionality need to be implemented at the proxy layer to some extent? I don't have full insight into what happens across all layers and thus I don't know if that would be necessary.

- **Tab List Management**: Tab list packets might need to be altered to reflect vanished players only to those with the necessary permissions.
- **Packet Filtering**: Various packets from vanished clients would need to be filtered and only sent to players with permission to see them.
- **State Updates**: Additional packets would be required upon vanish/unvanish to update all clients with the player's new state. This ensures players don't appear to "float in the air" when vanishing, for example.
- **Collision and Interaction**:
  - Auto-completion and tab suggestions might need to exclude vanished players.
  - Entity collision, arrow collision (even though not implemented yet), and player PvP would need to respect the vanished state.

**Comment by TestingPlant** [comment]
> Would vanish functionality need to be implemented at the proxy layer to some extent?

We might need a version of the `BroadcastGlobal` server to proxy packet that can exclude multiple users (the ones with permissions to view vanished players) when broadcasting the packets for removing the player and another version which only includes admins when broadcasting the movement packets of vanished players. Other than that, I don't think there would need to be special handling of vanished players at the proxy

**Comment by andrewgazelka** [comment]
> > Would vanish functionality need to be implemented at the proxy layer to some extent?
> 
> We might need a version of the `BroadcastGlobal` server to proxy packet that can exclude multiple users (the ones with permissions to view vanished players) when broadcasting the packets for removing the player and another version which only includes admins when broadcasting the movement packets of vanished players. Other than that, I don't think there would need to be special handling of vanished players at the proxy

yeaaaa ok this is getting complicated fast 🤔

**Comment by GroobleDierne** [comment]
I think the group solution makes more sense it would allow us to do something like the Audiences system in KyoriAdventureAPI but with packets.
So in an event, you could have the "player" audience which is the basic one, a "spectator" or "camera" audience which could, for instance, see players highlighted, see different scoreboards with stats about the current state of the event, or see particle trails indicating where arrows came from etc...

**Comment by andrewgazelka** [comment]
Well, I think having a vanish command is important. I don't think that it should be prioritized because there are other much more important things to do, so I'm going to close this issue for now. But when other things are completed, I am down to reopen this.
