### ISSUE TITLE
Refactor the feature list

### ISSUE THREAD

**Issue by iliya-malecki** [andrewgazelka/hyperion#591]
As a random person who isnt familiar with the project, i would love to be able to see what this server implementation supports and what it doesnt. I have zero knowledge about minecraft server internals - for example, i didnt know lighting calculations are server side :) Because of that, the list of already implemented features isnt very informative to me because i dont understand the scope - thats why i think refactoring it into checkboxes and leaving some unticked as "not implemented yed" or "not planned" (or some other alternative format, maybe a table?) is a good idea!

**Comment by andrewgazelka** [comment]
> As a random person who isnt familiar with the project, i would love to be able to see what this server implementation supports and what it doesnt. I have zero knowledge about minecraft server internals - for example, i didnt know lighting calculations are server side :) Because of that, the list of already implemented features isnt very informative to me because i dont understand the scope - thats why i think refactoring it into checkboxes and leaving some unticked as "not implemented yed" or "not planned" (or some other alternative format, maybe a table?) is a good idea!

I'm trying to completely understand what you are looking for in this instance. I can refactor to a checkboxes approach, but I am unsure these will add the "context" you are looking for. For instance, we already list that we have lighting, but adding a checkbox would not make it is clear it is server-side.

<img width="456" alt="image" src="https://github.com/user-attachments/assets/c23f5194-d868-4e96-9032-569826cfe21a">

Do you have any thoughts?

**Comment by iliya-malecki** [comment]
Oh sorry, I think I didn't explain clearly. Turning a "lighting" bullet point into a checkbox of course doesn't add context, but the list of unchecked boxes does. As in, these 7 milestones are reached, and the other 3 still aren't. Of course the amount of effort is different for every milestone, but at least it gives a rough idea about the project completeness

**Comment by andrewgazelka** [comment]
thoughts on it now @iliya-malecki ?

**Comment by iliya-malecki** [comment]
Wow I wasn't ready for how complete this project is. Very cool stuff, thank you!

**Comment by andrewgazelka** [comment]
:) 🫶
