### ISSUE TITLE
fix respawn teleportation

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#606]
> When changing class with the command it triggers the anti-cheat if it wants to teleport you too far.

- because respawn packet respawns player at the location set by respawn packet whch is often really far away (so basically teleport)

possible fix:
- on respawn change the players location to desired respawn location before respawning

# Future
- in future players should respawn on death also based on clustering of where their team mates are in the map
  - basically a guassian probability distribution or something? (can be way more simple) ... and probably _should_ be as we want to do things as fast as possible

![image](https://github.com/user-attachments/assets/1824fc1a-7019-486b-8e69-64b49aa2d6fd)

**Comment by Kumpelinus** [comment]
I was just about to take a look at this but does the commit https://github.com/andrewgazelka/hyperion/commit/9eb8a7996719444922db6ea7fcb10aa73e8aac40 already fix this?

**Comment by Kumpelinus** [comment]
I just saw that you changed the title. Since the class changing does not change your position anymore (I assume that is intended) it does not happen for that specific case anymore. Maybe it does not fix the case of a player dying though.

**Comment by andrewgazelka** [comment]
yea I fixed this
