### ISSUE TITLE
potential SIMD alignment crash?

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#608]
If the server crashes please give log/stacktrace

> Did you change something about xp handling which broke hyperion?
> Huh
> Wtf it works now
> sus

**Comment by Kumpelinus** [comment]
```
thread 'main' panicked at crates/hyperion/src/egress/sync_entity_state.rs:73:25:
assertion `left == right` failed: prev_xp is not 64-byte aligned
  left: 16
 right: 0
```

**Comment by Kumpelinus** [comment]
[log.txt](https://github.com/user-attachments/files/17940886/log.txt)
@andrewgazelka that is the backtrace I got.

**Comment by Kumpelinus** [comment]
I just tried using the release profile. When using that **it does work** as intended. But after switching back to the development profile it occurred to me again.

**Comment by andrewgazelka** [comment]
> I just tried using the release profile. When using that **it does work** as intended. But after switching back to the development profile it occurred to me again.

The asserts are debug asserts meaning they should never go off but are compiled out in release mode

**Comment by Kumpelinus** [comment]
It "working" was more like a workaround for me that I wanted to share (since I was not able to work on stuff with the SIMD crashing). Also it was a good hint to what could cause it.
