### ISSUE TITLE
Fix issues caused by class selection

### ISSUE THREAD

**Issue by Kumpelinus** [andrewgazelka/hyperion#613]
If you try to "switch" to the class that you already have (of your current team) it does not give you the kit.
Instead it completely clears your inventory.

**Comment by Kumpelinus** [comment]
It seems to be just a wrong packet being sent (or not being sent) since other players can see you holding the items while you can't see them yourself.

**Comment by Kumpelinus** [comment]
I found a few more Issues with this as well.
* It also resets the xp in the client's xp bar. However it does not reset the xp stat on the server so you will get it back upon gaining xp again (So it is just visual). 
* It removes you from your own tab-list which might indicate further problems (can't confirm that yet).

**Comment by andrewgazelka** [comment]
> I found a few more Issues with this as well.
> 
> * It also resets the xp in the client's xp bar. However it does not reset the xp stat on the server so you will get it back upon gaining xp again (So it is just visual).
> * It removes you from your own tab-list which might indicate further problems (can't confirm that yet).

yea changing the lpayer skin requires "killing and respawning htem" client side which can break al ot of thing... we have to send all the packets including XP packets to make sure their state after respawn is the same as before respawn

**Comment by Kumpelinus** [comment]
The class selection itself resets your inventory.
And the code

```rust
.observer::<flecs::OnSet, (
    &Xp,                  //                  (0)
    &UpgradedTo,          //                  (1)
    &Class,               //                  (2)
    &Team,                //                  (3)
    &MainBlockCount,      //                  (4)
    &mut PlayerInventory, //             (5)
)>()
```
normally observes this and thus gives you the equipment you the equipment.

But since neither your team nor your class changes in the case of selecting the same class + team it does not trigger the `apply_inventory` method and that leads to your inventory staying empty.

We could either:
* change the observer to react to an event by the command **OR**
* just check for the same team + class when running the command.

I prefer the latter one since you can also add a error message very easily that way.

**Comment by andrewgazelka** [comment]
pretty sure this issue is fixed now
