### ISSUE TITLE
Command completion permission check

### ISSUE THREAD

**Issue by Kumpelinus** [andrewgazelka/hyperion#616]
Filter the command completions / available commands list to only show a user the commands they actually have access to. Since most of the commands in the event are moderation commands showing everything will make it cluttered otherwise.

**Comment by Kumpelinus** [comment]
FYI: I have already been working on this. I will probably have a PR ready by today or tomorrow.

**Comment by andrewgazelka** [comment]
oh yea awesome :) 👍
