### ISSUE TITLE
add GUI API

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#618]
basically we want a GUI API...

you can create GUIs and click around through them and they do actions and stuff

related:

we already have an API for doing actions when people right click on items? maybe expand upon this? unsure if this pattern is good or not... but we want players to be able to right click items and it opens an inventory GUI where players can click on items to use their points, etc

https://github.com/andrewgazelka/hyperion/blob/0bf0af78a0cfdb2277fa6a76ffcfffa39e7cb97f/crates/hyperion-item/src/builder.rs#L153-L162

https://github.com/andrewgazelka/hyperion/blob/5400609658bf051dc842c2d159ab8556a1e27c5c/crates/hyperion-rank-tree/src/lib.rs#L69-L76

**Comment by Tebarem** [comment]
this issue is done as well. unless something else is needed
