### ISSUE TITLE
Players Not in Sync/Updating

### ISSUE THREAD

**Issue by Tebarem** [andrewgazelka/hyperion#676]
Player Position, Yaw, Pitch and Pose is not being updated. I heard someoen was already working on it so Im just putting this issue here.

**Comment by andrewgazelka** [comment]
> Player Position, Yaw, Pitch and Pose is not being updated. I heard someoen was already working on it so Im just putting this issue here.

hmmm? then how do bows kinda work if this is the case?

**Comment by Kumpelinus** [comment]
@andrewgazelka, @Tebarem and me already took a look at this Issue. At the moment nothing sync related is working anymore.

**Comment by andrewgazelka** [comment]
> @andrewgazelka, @Tebarem and me already took a look at this Issue. At the moment nothing sync related is working anymore.

hmmm let me look at this briefly seems something I can fix easily and probs was caused by me

**Comment by Kumpelinus** [comment]
Something merge related afaik. We already exactly know what caused it though.

**Comment by andrewgazelka** [comment]
> Player Position, Yaw, Pitch and Pose is not being updated. I heard someoen was already working on it so Im just putting this issue here.

This cannot be right. try doing `/spawn` ... the entities follow

**Comment by Kumpelinus** [comment]
@andrewgazelka I have given you some details via discord.

**Comment by Tebarem** [comment]
I think what happened is when i added the projectile_sync in my head i added a filter for `EntityKind::Arrow` and it mixed with whatever was already there. Then either i removed it or someone else did and it all got mangled there.

**Comment by andrewgazelka** [comment]
we talked about this @Tebarem will make a video of me solving it soon

**Comment by Tebarem** [comment]
@andrewgazelka i fixed it partially i added back the old `entity_state_sync` now the issue is gravity doesn't seem to be applying

**Comment by Tebarem** [comment]
@andrewgazelka how are we doing physics simulation?

**Comment by Tebarem** [comment]
Looks like we arent doing any physics sim. I think that should be the next big thing we do it will sort out all of these issues

**Comment by andrewgazelka** [comment]
https://github.com/andrewgazelka/hyperion/pull/691 mostly fixes

**Comment by andrewgazelka** [comment]
recommend looking at https://www.flecs.dev/explorer

**Comment by andrewgazelka** [comment]
still maybe need to fix yaw for players? idk

**Comment by Kumpelinus** [comment]
#696 will fix it most likely

**Comment by Tebarem** [comment]
fixed in #696
