### ISSUE TITLE
ability to bundle proxy and server together

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#692]
- make proxy a lib
- bundle proxy together with server
- by DEFAULT make server communicate over Unix sockets between them
  - this is proably easiest way to do it short term. long term could
    communicate with rust channels too I suppose but UNIX sockets are
    definitely fast enough and reduce two different code paths
  - of course, in production, we will still advise using two different
    processes (esp for large events)

# Reasoning
- makes it easier to develop (especially for new contributors)
- makes it easier to do continuous deployment... imagine we have a
  Minecraft server that is always running that will always be running
  the latest version of the event server for alpha testing.

**Comment by andrewgazelka** [comment]
think @Kumpelinus was talking about this... think would help contributors. feel free to do this whenever you like. (not necessarily a backlog item)

**Comment by Kumpelinus** [comment]
Yeah. I know that quite a bunch of people had Issues understanding hyperion's structure. Since it could be discouraging for new contributors it would be a Huge plus to simplify it for development purposes (and maybe smaller-ish projects)

**Comment by andrewgazelka** [comment]
going to close this for now since event is so close. then likely re-open after event.
